import LocalizedStrings from 'react-native-localization';

const String = new LocalizedStrings({
  en: {
    first: 'Email must have a number and special character.',
    second: 'Email is required',
    passwordMatch: 'Please enter a password with at least 8 characters',
    passwordRequired: 'Enter password',
    confirmPasswordRequired: 'Enter confirm password',
    confirmPasswordMatch: 'Password do not match',
    welcomeText: 'MABUHAY!',
    welcomeSubText: 'Welcome to the home of Filipino Live Sports',
    forgotFirstText: 'Forgot your password?',
    forgotSecondText: 'Enter your registered email',
    buttonTitleContinue: 'CONTINUE',
    verifyFirstText: 'Verify your OTP',
    signUpFirstText: 'Verification was successful!',
    signUpSecondText: "Let’s set up your account",
    CheckText1: 'I agree to Pilipina’s ',
    CheckText2: 'Terms of Use ',
    CheckText3: 'Privacy Policy',
    CheckText4: 'and have read and understood the Cignal TV Inc’s',
    SignInText: 'Sign In here',
    AlreadyText: 'Already have an Account?',
    ResendOtpText: 'Resend OTP in 57 secs',
    OtpText: 'OTP was sent to',
    PaymentText: 'Welcome to Pilipinas Live',
    PaymentSubText: 'The Ultimate destination for Filipino Sports Fans',
    PaymentDescriptionText: 'Enjoy LIVE games, catch-ups and an extensive library of exclusive video content from the Philippines Top sports leagues for only',
    CostText: '₱ 199/ month',
    StartYourTrailText: 'Start your 3-day free trial',
    LiteVersionText: 'try the LITE version for free',
    Privacypolicy: 'Privacy Policy',
    Terms_condition: 'T & C',
    PayDetailsSubscribe: 'Subscribe to the plan below to access your',
    PayDetailsTrail: '3-DAY FREE TRIAL',
    Premium: 'Premium',
    PremiumDetails: 'Get in the game for only ₱199 a month and watch your favourite sports and leagues in action anytime, anywhere',
    CancelText: 'You can cancel anytime within the trial period if you wish to discontinue your subscription',
    FeatureTitle1: 'Live games and Catch-ups',
    FeatureDetail1: 'Full access to Live and Upcoming games with all the Highlights, Replays and Trending News',
    TaptoPay: 'tap to pay',
    ColdStart: 'THAT’S THE SPIRIT',
    ColdStart2: 'You’re all set for Jam-Packed Sports Action',
    Skip: 'SKIP',
    SportSelect: 'Please select your choice of Sport to continue ',
    Select1: 'Select Atleast 1',
    badminton: 'Badminton',
    hockey: 'Hockey',
    volleyball: 'VolleyBall',
    baseball: 'Baseball',
    basketball: 'Basketball',
    tennis: 'Tennis',
    boxing: 'Boxing',
    football: 'Football',
    golf: 'golf',
  }
});

export default String;